# @package _global_

defaults:
  - _self_
  - data: data # choose datamodule with `test_dataloader()` for evaluation
  - model: model
  - logger: tensorboard
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: "[val, unet]"

# passing checkpoint path is necessary for evaluation
ckpt_path: logs/train/runs/2024-03-06_17-15-21/checkpoints/epoch_1083.ckpt
